vqgan_ckpt: ./checkpoints/vq_gan/DEFAULT/lightning_logs/version_0/checkpoints/latest_checkpoint-v2.ckpt 


# 这些参数会根据VQ-GAN编码后的实际尺寸动态设置
diffusion_img_size: null
diffusion_depth_size: null  
diffusion_num_channels: null
dim_mults: [1, 2, 4, 8]

# 数据路径
csv_path: /home/jz97/MRI_Diffusion/repo/3D_MRI_Diffusion/data/ADNI/ADNI.csv
results_folder: /home/jz97/MRI_Diffusion/repo/3D_MRI_Diffusion/checkpoints/ddpm/
results_folder_postfix: 'multi_gpu'

# 多GPU训练配置
batch_size: 8              # 每个GPU的batch size
num_workers: 8             # 每个GPU的worker数
gpus: 4                    # 使用的GPU数量

# 模型配置
denoising_fn: Unet3D
train_lr: 1e-4
timesteps: 1000
sampling_timesteps: 250
loss_type: l1
objective: pred_x0

# 训练配置  
train_num_steps: 1000
gradient_accumulate_every: 2
save_and_sample_every: 20
ema_decay: 0.995
amp: true                  # 开启混合精度训练
num_sample_rows: 2

# 其他配置
load_milestone: False
logger: wandb