name: DEFAULT
root_dir: /data0/projects/JingGPU/IUI_Datasets_Generation
csv_path: /home/jz97/mri_diffusion/3D_MRI_Diffusion/data/data.csv  # new input 
image_channels: 1
augmentation: True


# 新增的配置项
target_size: [192, 192, 192]
resize_mode: 'pad'  # 可选: 'pad', 'crop', 'stretch'
